apiVersion: batch/v1
kind: Job
metadata:
  name: app-perf-db-migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bundle", "exec", "rails", "db:migrate"]
          envFrom:
          - configMapRef:
              name: app-perf-config          
          - secretRef:
              name: app-perf-secrets              
      restartPolicy: Never
  backoffLimit: 0
