{{- if eq .Values.ingress.enabled true }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-perf
  labels:
    app.kubernetes.io/name: app-perf
    helm.sh/chart: app-perf
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - backend:
              serviceName: app-perf-website
              servicePort: http
  {{- end }}
{{- end }}