apiVersion: v1
kind: Secret
metadata:
  name: app-perf-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  SECRET_KEY_BASE: {{ .Values.secret_key_base | quote }}
  REDIS_URL: {{ .Values.redis_url | quote }}
  DATABASE_URL: {{ .Values.database_url | quote }}
  SMTP_USERNAME: {{ .Values.smtp_username | quote }}
  SMTP_PASSWORD: {{ .Values.smtp_password | quote }}